CFLAGS += -DJACOBIAN_COORDINATES
CFLAGS += -DWORDS_32_BITS 

ifeq ($(CURVE_PARAMS),)
  CURVE_PARAMS = SECP256R1
endif

# include curve files
ifeq ($(CURVE_PARAMS),SECP256R1)
CONTIKI_SOURCEFILES += secp256r1.c
endif

DEFINES += $(CURVE_PARAMS)
CFLAGS += ${addprefix -D, $(DEFINES)}

ecc_src += bigint.c ecc.c